# Options for ANTdongle Old 0fcf:1004
Options usbserial vendor=0x0fcf product=0x1004
# Options for ANTdongle Suunto 0fcf:1008
Options usbserial vendor=0x0fcf product=0x1008
# Options for ANTdongle Garmin 0fcf:1009
Options usbserial vendor=0x0fcf product=0x1009

